### PR TITLE
Typo fix in explanatory comment

### PR DESCRIPTION
**Pull request by NewEvolution**
it's vs its

### CODE REVIEW

**Comment by mpirnat** [comment]
Not sure why this is picking up the swallow and white space fixes again; I thought those had already been merged in a previous PR.

**Comment by gregmalcolm** [comment]
I think its happening because your pull request is off of your local master branch, same as your last PR. if you create a new branch and base your PR off of that the PR should only use the fresh commits. Do you want to give that a try?

**Comment by mpirnat** [comment]
I may have also messed things up by squashing the other PR when I merged it.

**Comment by NewEvolution** [comment]
OK, glad it's not just me being mildly confused about why those previously merged changes were showing up.  I'll re-submit with a different branch with only the new changes.

**Pull request closed without merging**
