### PR TITLE
add an assertion in about_lists.test_ranges_with_steps

### PR DESCRIPTION
**Pull request by cliftonmcintosh**
I found it a little hard to pick up on the reverse ranges and steps, and I experimented with how this worked. An assertion with a descending range that did not go into negatives and a step of -1 helped me.

### CODE REVIEW

**Comment by dstanek** [comment]
Should the new assertions go before the existing negative stepped assertions? I think it would be better to introduce the simpler assertion first.

**Comment by gregmalcolm** [comment]
Looks like a nice addition, but @dstanek has a point. Are you still up for changing the order? I know this has been hanging for a while, sorry about that. :)

**Comment by cliftonmcintosh** [comment]
Good point. I have moved the simpler assertion so that it is first.

**Comment by gregmalcolm** [comment]
Thanks!

One other small thing is I notice the Python2 flavor is wrapped in a List. Either all or none should be wrapped in List I think? It's a little inconsistent with just the one.

I believe the Python3 flavor uses List wrappings because they don't work without List.

**Comment by cliftonmcintosh** [comment]
updated so that the python2 version does not have the new range wrapped in a list.

**Comment by gregmalcolm** [comment]
Thanks for hanging in there!

**Pull request merged**
