### PR TITLE
added coroutines to koans

### PR DESCRIPTION
**Pull request by sak96**
added some ideas for koans from https://www.dabeaz.com/coroutines/Coroutines.pdf

### CODE REVIEW

**Comment by sak96** [comment]
The build is failing when download of python3.2 python 3.3. Can someone help ?

**Comment by hugovk** [comment]
Python 3.2 and 3.3 are looong EOL:

Version | Release date | Supported until
--- | ---------- | ----------
2.7 | 2010-07-03 | 2020-01-01
3.2 | 2011-02-20 | 2016-02-27
3.3 | 2012-09-29 | 2017-09-29
3.4 | 2014-03-16 | 2019-03-16

Source: https://en.wikipedia.org/wiki/CPython#Version_history

I've created PR #207 to drop them.

**Comment by sak96** [comment]
@gregmalcolm can you please guide me what to do ?

**Comment by k-a-suvorov** [comment]
Спасибо, Ваше письмо получено.
С уважением, Константин Суворов

**Comment by sak96** [comment]
abandoning the pull request

**Pull request closed without merging**
